---
apiVersion: v1
kind: Secret
metadata:
  name: github-token-secret
type: Opaque
data:
  GITHUB_TOKEN: git_token
---
apiVersion: v1
kind: Secret
metadata:
  name: ssh-keys-secret
type: Opaque
data:
  SSH_PUBLIC: ssh_public
  SSH_PRIVATE: ssh_private
